#ifndef AKUMULI_VERSION_H
#define AKUMULI_VERSION_H

#define AKUMULI_MAJOR_VERSION 0
#define AKUMULI_MINOR_VERSION 1
#define AKUMULI_PATCH_VERSION 0

#define AKUMULI_VERSION_00100 10
#define AKUMULI_VERSION 10

#endif
